TrajectoryPlannerROS:

# Robot Configuration Parameters
  acc_lim_x:                    10.0
  acc_lim_y:                    0.0
  acc_lim_theta:                3.5
  max_vel_x:                    0.6
  min_vel_x:                    0.05
  max_rotational_vel:           1.0
  min_in_place_vel_theta:       0.05
  escape_vel:                   -0.8
  holonomic_robot:              false

  # The following parameters are only used if holonomic_robot is set to true:
  y_vels: [0.0, 0.0, 0.0, 0.0]

  # Goal Tolerance Parameters
  yaw_goal_tolerance:           0.10
  xy_goal_tolerance:            0.10
  latch_xy_goal_tolerance:      true

  # Forward Simulation Parameters
  sim_time:                     4.5
  sim_granularity:              0.25
  angular_sim_granularity:      0.05
  vx_samples:                   20
  vtheta_samples:               40
  

  # Trajectory Scoring Parameters
  meter_scoring:                true
  path_distance_bias:           1.0  #path_distance_bias 5.0
  goal_distance_bias:           0.8  #goal_distance_bias 0.8
  occdist_scale:                0.01
  heading_lookahead:            0.325
  heading_scoring:              true
  heading_scoring_timestep:     0.8
  dwa:                          true
  publish_cost_grid_pc:         false

  # Oscillation Prevention Parameters
  oscillation_reset_dist:       0.1

  # Global Plan Parameters
  


  ### Map management parameters ###
  # Located in costmap_global.yaml & _local.yaml


DWAPlannerROS:
  
  xy_goal_tolerance: 0.1 #0.1
  yaw_goal_tolerance: 0.1 #0.1 
  #latch_xy_goal_tolerance: true #no esta

  # Forward Simulation Parameters
  use_dwa: true #true
  sim_time: 4.5 #1.7
  sim_granularity: 0.025 #0.025
  angular_sim_granularity: 0.017 #0.017
  vx_samples: 20 #3
  vy_samples: 20 #10
  vth_samples: 40 #20

  # Trajectory scoring parameters
  #meter_scoring: true #false.
  path_distance_bias: 32 #32
  goal_distance_bias: 20 #24
  occdist_scale: 0.01 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  #forward_point_distance: 0.325
  #stop_time_buffer: 0.20
  #scaling_speed: 0.25
  #max_scaling_factor: 0.20

  # Robot Configuration Parameters
  acc_lim_x: 1.0  #2.5
  acc_lim_y: 1.0  #2.5  
  acc_lim_theta:  1.0 #3.2
  acc_lim_trans:  0.1 #0.1
  max_trans_vel: 10.0 #10.0
  min_trans_vel: 0.1  #0.1
  max_vel_x: 0.7     #0.7
  min_vel_x: -0.7    #-0.7
  max_vel_y: 0.0     #0.7
  min_vel_y: 0.0    #-0.7
  max_rot_vel: 3.0  #1.0
  min_rot_vel: 0.4  #0.4
   
  #oscillation_reset_dist: 0.05 #0.05
  #oscillation_reset_angle: 0.20 #0.2
 
  #trans_stopped_vel: 0.1 #0.1
  #rot_stopped_vel: 0.1   #0.1

  prune_plan: false