map_type: voxel
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: true #false
transform_tolerance: 0.5
meter_scoring: true

#footprint: [[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]
robot_radius: 0.125
footprint_padding: 0.05

plugins:
  - { name: static_layer, type: "costmap_2d::StaticLayer" }
  - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  - { name: voxel_layer, type: "costmap_2d::VoxelLayer" }
  - { name: inflater_layer, type: "costmap_2d::InflationLayer" }
  - { name: social_layer, type: "social_navigation_layers::ProxemicLayer" }
  # - { name: social_layer, type: "social_navigation_layers::PassingLayer" }

#inflation_radius: 0.55 #0.1
cost_scaling_factor: 5.0 #2.2
track_unknown_space: true

obstacles_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: laser_range_sensor
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true #default to true

voxel_layer:
  enabled: true
  origin_z: 0
  z_resolution: 0.05
  publish_voxel_map: true
  combination_method: 1
  z_voxels: 10
  unknown_threshold: 2
  observation_sources: kinect_camera
  kinect_camera:
    sensor_frame: gz_kinect_link
    data_type: PointCloud2
    topic: /uvbot/point_cloud
    marking: true
    clearing: true
    min_obstacle_height: 0.1
    max_obstacle_height: 2.0

social_layer:
  enabled: true
  cutoff: 10
  amplitude: 77
  covariance: 0.25
  factor: 5.0
  keep_time: 0.75