global_costmap:
  global_frame: map #put map or odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  width: 40.0
  height: 40.0
  resolution: 0.05
  static_map: false    #if im using a map_server set to true
  rolling_window: false
  inflation_radius: 0.5