base_global_planner: navfn/NavfnROS
#base_local_planner: dwa_local_planner/DWAPlannerROS
base_local_planner: base_local_planner/TrajectoryPlannerROS

recovery_behaviors: [               {
                                      name: conservative_reset,
                                      type: clear_costmap_recovery/ClearCostmapRecovery
                                    }, {
                                      name: rotate_recovery1,
                                      type: rotate_recovery/RotateRecovery
                                    }, {
                                      name: aggressive_reset,
                                      type: clear_costmap_recovery/ClearCostmapRecovery
                                    }, {
                                      name: rotate_recovery2,
                                      type: rotate_recovery/RotateRecovery
                                    }]

planner_frequency:          0     # Global plan updates on new goal or path blocked only
controller_frequency:       20
planner_patience:           5.0
controller_patience:        3.0
conservative_reset_dist:    2.0
agresive_reset_dist:        0.0
recovery_behavior_enabled:  true
clearing_rotation_allowed:  true
shutdown_costmaps:          false
oscillation_timeout:        4.0
oscillation_distance:       0.1

